// GENERATED BY aic — DO NOT EDIT. Source of truth: src/screens/*.ui.yaml and src/components/*.ui.yaml
import SwiftUI
import Combine

enum OscarRoute: Hashable {
    case dashboard
    case login
    case showcase
}

@MainActor
final class OscarRouter: ObservableObject {
    @Published var path: [OscarRoute] = []
    private let animationsEnabled = false

    func push(_ route: OscarRoute) {
        update { path.append(route) }
    }

    func pop() {
        update { if !path.isEmpty { path.removeLast() } }
    }

    private func update(_ change: () -> Void) {
        if animationsEnabled {
            change()
            return
        }
        var transaction = Transaction(animation: nil)
        transaction.disablesAnimations = true
        withTransaction(transaction) { change() }
    }
}

@main
struct ParityApp: App {
    @StateObject private var router = OscarRouter()

    var body: some Scene {
        WindowGroup {
            ZStack(alignment: .topLeading) {
                NavigationStack(path: $router.path) {
                    LoginView(actions: LoginActionsImpl(), router: router)
                        .toolbar(.hidden, for: .navigationBar)
                        .navigationDestination(for: OscarRoute.self) { route in
                            switch route {
                            case .dashboard:
                                DashboardView(actions: DashboardActionsImpl(), router: router)
                                    .padding(.top, 56)
                                    .toolbar(.hidden, for: .navigationBar)
                            case .login:
                                LoginView(actions: LoginActionsImpl(), router: router)
                                    .padding(.top, 56)
                                    .toolbar(.hidden, for: .navigationBar)
                            case .showcase:
                                ShowcaseView(actions: ShowcaseActionsImpl(), router: router)
                                    .padding(.top, 56)
                                    .toolbar(.hidden, for: .navigationBar)
                            }
                        }
                }

                if !router.path.isEmpty {
                    Button {
                        router.pop()
                    } label: {
                        Text("‹")
                            .font(Theme.Typography.title)
                            .foregroundStyle(Theme.Colors.textPrimary)
                            .frame(width: 48, height: 48)
                    }
                    .buttonStyle(.plain)
                    .accessibilityLabel("Back")
                    .padding(.leading, 8)
                    .padding(.top, 8)
                    .zIndex(1)
                }
            }
        }
    }
}
