// GENERATED BY aic — DO NOT EDIT. Source of truth: src/screens/*.ui.yaml and src/components/*.ui.yaml
import SwiftUI

protocol ShowcaseActions {
}

struct ShowcaseView: View {
    @State private var showImage: Bool = true
    let actions: ShowcaseActions
    @ObservedObject var router: OscarRouter

    var body: some View {
        GeometryReader { proxy in
            ZStack(alignment: .center) {
                Theme.Colors.background
                    .ignoresSafeArea()
                VStack(alignment: .center, spacing: Theme.Spacing.normal) {
                    HStack(alignment: .center, spacing: Theme.Spacing.tight) {
                        Text("Swift")
                            .font(Theme.Typography.heading)
                            .foregroundStyle(Theme.Colors.textPrimary)
                        Spacer()
                        Text("Kotlin")
                            .font(Theme.Typography.heading)
                            .foregroundStyle(Theme.Colors.textPrimary)
                    }
                    if showImage == true {
                        AsyncImage(url: URL(string: "https://example.com/oscarui.png")) { image in
                            image.resizable().scaledToFill()
                        } placeholder: {
                            Color.gray.opacity(0.2)
                        }
                        .frame(height: 180)
                        .clipShape(RoundedRectangle(cornerRadius: Theme.Radius.large))
                    }
                }
                .padding(Theme.Spacing.loose)
            }
            .frame(width: proxy.size.width, height: proxy.size.height)
        }
        .background(Theme.Colors.background)
        .ignoresSafeArea()
    }
}
