// GENERATED BY aic — DO NOT EDIT. Source of truth: src/screens/*.ui.yaml and src/components/*.ui.yaml
import Foundation

protocol DashboardActions {
    func openShowcase()
    func selectProject()
}

protocol LoginActions {
    func login()
    func forgotPassword()
}

protocol ShowcaseActions {
}

final class RuntimeNativeActions {
    private let dashboard = DashboardActionsImpl()
    private let login = LoginActionsImpl()
    private let showcase = ShowcaseActionsImpl()

    func invoke(screen: String, action: String) {
        switch (screen, action) {
        case ("Dashboard", "openShowcase"):
            dashboard.openShowcase()
        case ("Dashboard", "selectProject"):
            dashboard.selectProject()
        case ("Login", "login"):
            login.login()
        case ("Login", "forgotPassword"):
            login.forgotPassword()
        default:
            print("OscarUI runtime: unknown native action \(screen).\(action)")
        }
    }
}
