import { camel, HEADER } from './util.mjs';

export function emitAppSwift(screens, appName = 'OscarUI', config = {}) {
  const entry = screens.find(({ ir }) => ir.entry)?.ir ?? screens[0]?.ir;
  if (!entry) throw new Error('ios shell: at least one screen is required');
  const routes = screens.map(({ ir }) => ir.screen);
  const animationsEnabled = config.navigation?.animation !== 'none';

  const lines = [
    `// ${HEADER}`,
    'import SwiftUI',
    'import Combine',
    '',
    'enum OscarRoute: Hashable {',
    ...routes.map(screen => `    case ${camel(screen)}`),
    '}',
    '',
    '@MainActor',
    'final class OscarRouter: ObservableObject {',
    '    @Published var path: [OscarRoute] = []',
    `    private let animationsEnabled = ${animationsEnabled ? 'true' : 'false'}`,
    '',
    '    func push(_ route: OscarRoute) {',
    '        update { path.append(route) }',
    '    }',
    '',
    '    func pop() {',
    '        update { if !path.isEmpty { path.removeLast() } }',
    '    }',
    '',
    '    private func update(_ change: () -> Void) {',
    '        if animationsEnabled {',
    '            change()',
    '            return',
    '        }',
    '        var transaction = Transaction(animation: nil)',
    '        transaction.disablesAnimations = true',
    '        withTransaction(transaction) { change() }',
    '    }',
    '}',
    '',
    '@main',
    `struct ${appName}: App {`,
    '    @StateObject private var router = OscarRouter()',
    '',
    '    var body: some Scene {',
    '        WindowGroup {',
    '            ZStack(alignment: .topLeading) {',
    '                NavigationStack(path: $router.path) {',
    `                    ${entry.screen}View(actions: ${entry.screen}ActionsImpl(), router: router)`,
    '                        .toolbar(.hidden, for: .navigationBar)',
    '                        .navigationDestination(for: OscarRoute.self) { route in',
    '                            switch route {',
    ...routes.map(screen => `                            case .${camel(screen)}:\n                                ${screen}View(actions: ${screen}ActionsImpl(), router: router)\n                                    .padding(.top, 56)\n                                    .toolbar(.hidden, for: .navigationBar)`).flatMap(value => value.split('\n')),
    '                            }',
    '                        }',
    '                }',
    '',
    '                if !router.path.isEmpty {',
    '                    Button {',
    '                        router.pop()',
    '                    } label: {',
    '                        Text("‹")',
    '                            .font(Theme.Typography.title)',
    '                            .foregroundStyle(Theme.Colors.textPrimary)',
    '                            .frame(width: 48, height: 48)',
    '                    }',
    '                    .buttonStyle(.plain)',
    '                    .accessibilityLabel("Back")',
    '                    .padding(.leading, 8)',
    '                    .padding(.top, 8)',
    '                    .zIndex(1)',
    '                }',
    '            }',
    '        }',
    '    }',
    '}',
    '',
  ];

  return lines.join('\n');
}
