export function indent(lines, level) {
  const pad = '    '.repeat(level);
  return lines.map(l => (l === '' ? '' : pad + l));
}

export function esc(s) {
  return String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

export function pascal(s) {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

export function camel(s) {
  return s.charAt(0).toLowerCase() + s.slice(1);
}

export const HEADER = 'GENERATED BY aic — DO NOT EDIT. Source of truth: src/screens/*.ui.yaml and src/components/*.ui.yaml';
