// GENERATED BY aic — DO NOT EDIT. Source of truth: src/screens/*.ui.yaml and src/components/*.ui.yaml
package app.generated

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent { RuntimeOscarApp() }
    }
}
