// GENERATED BY aic — DO NOT EDIT. Source of truth: src/screens/*.ui.yaml and src/components/*.ui.yaml
package app.generated

interface DashboardActions {
    fun openShowcase()
    fun selectProject()
}

interface LoginActions {
    fun login()
    fun forgotPassword()
}

interface ShowcaseActions {
}

class RuntimeNativeActions {
    private val dashboard = DashboardActionsImpl()
    private val login = LoginActionsImpl()
    private val showcase = ShowcaseActionsImpl()

    fun invoke(screen: String, action: String) {
        when ("$screen.$action") {
            "Dashboard.openShowcase" -> dashboard.openShowcase()
            "Dashboard.selectProject" -> dashboard.selectProject()
            "Login.login" -> login.login()
            "Login.forgotPassword" -> login.forgotPassword()
            else -> android.util.Log.w("OscarUI", "Unknown runtime action $screen.$action")
        }
    }
}
