// GENERATED BY aic — DO NOT EDIT. Source of truth: src/screens/*.ui.yaml and src/components/*.ui.yaml
package app.generated

import android.content.Context
import android.os.Handler
import android.os.Looper
import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.runtime.snapshots.SnapshotStateMap
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.navigation.NavHostController
import androidx.navigation.compose.NavHost
import androidx.navigation.compose.composable
import androidx.navigation.compose.currentBackStackEntryAsState
import androidx.navigation.compose.rememberNavController
import coil.compose.AsyncImage
import org.json.JSONArray
import org.json.JSONObject
import java.io.File
import java.net.HttpURLConnection
import java.net.URL
import java.security.MessageDigest

private const val RUNTIME_API = 1
private const val UI_SCHEMA_VERSION = 1

private fun sha256(value: String): String = MessageDigest.getInstance("SHA-256")
    .digest(value.toByteArray(Charsets.UTF_8))
    .joinToString("") { "%02x".format(it) }

private fun JSONObject.objects(key: String): List<JSONObject> {
    val array = optJSONArray(key) ?: return emptyList()
    return (0 until array.length()).mapNotNull { array.optJSONObject(it) }
}

private fun JSONObject.string(key: String, fallback: String = ""): String = optString(key, fallback)

class RuntimeBundle(data: ByteArray) {
    val contentHash: String
    val manifest: JSONObject
    val payload: JSONObject

    init {
        val envelope = JSONObject(data.toString(Charsets.UTF_8))
        contentHash = envelope.getString("contentHash")
        val content = envelope.getString("content")
        require(contentHash == "sha256:${sha256(content)}") { "runtime bundle hash mismatch" }
        val decoded = JSONObject(content)
        manifest = decoded.getJSONObject("manifest")
        payload = decoded.getJSONObject("payload")
        val compatibility = manifest.getJSONObject("compatibility")
        require(manifest.getString("format") == "oscarui.runtime.bundle" && manifest.getInt("bundleVersion") == 1)
        require(RUNTIME_API in compatibility.getInt("minRuntimeApi")..compatibility.getInt("maxRuntimeApi"))
        require(compatibility.getInt("uiSchemaVersion") == UI_SCHEMA_VERSION)
    }

    val entryScreen: String get() = manifest.getString("entryScreen")
    val screens: List<JSONObject> get() = payload.objects("screens")
    val components: List<JSONObject> get() = payload.objects("components")
    val tokens: JSONObject get() = payload.getJSONObject("tokens")
    val appConfig: JSONObject get() = payload.getJSONObject("appConfig")
    val navigationAnimationsEnabled: Boolean get() = appConfig.optJSONObject("navigation")?.string("animation", "platform") != "none"
    fun screen(name: String): JSONObject? = screens.firstOrNull { it.string("screen") == name }
    fun component(name: String): JSONObject? = components.firstOrNull { it.string("component") == name }
}

class RuntimeBundleLoader(private val context: Context) {
    private val directory = File(context.filesDir, "runtime")
    private val current = File(directory, "current.json")
    private val lastGood = File(directory, "last-good.json")

    fun loadInitial(): RuntimeBundle {
        for (file in listOf(current, lastGood)) {
            if (file.exists()) runCatching { return RuntimeBundle(file.readBytes()) }
        }
        return RuntimeBundle(context.assets.open("oscarui.runtime.json").use { it.readBytes() })
    }

    fun activate(data: ByteArray): RuntimeBundle {
        val bundle = RuntimeBundle(data)
        directory.mkdirs()
        if (current.exists()) current.copyTo(lastGood, overwrite = true)
        val pending = File(directory, "current.pending")
        pending.writeBytes(data)
        if (current.exists()) current.delete()
        require(pending.renameTo(current)) { "could not activate runtime bundle" }
        return bundle
    }
}

class RuntimeBundleStore(private val context: Context) {
    private val loader = RuntimeBundleLoader(context)
    var bundle by mutableStateOf(loader.loadInitial())
        private set

    fun fetchRemoteUpdateIfConfigured() {
        val runtime = bundle.appConfig.optJSONObject("runtime") ?: return
        if (!runtime.optBoolean("allowRemoteUpdates")) return
        val url = runtime.string("remoteBundleURL")
        if (!url.startsWith("https://")) return
        val timeout = runtime.optInt("requestTimeoutSeconds", 15) * 1000
        Thread {
            runCatching {
                val connection = URL(url).openConnection() as HttpURLConnection
                connection.connectTimeout = timeout
                connection.readTimeout = timeout
                connection.setRequestProperty("If-None-Match", bundle.contentHash)
                if (connection.responseCode == HttpURLConnection.HTTP_NOT_MODIFIED) return@runCatching
                require(connection.responseCode in 200..299)
                val data = connection.inputStream.use { it.readBytes() }
                val next = RuntimeBundle(data)
                if (next.contentHash != bundle.contentHash) {
                    Handler(Looper.getMainLooper()).post { bundle = loader.activate(data) }
                }
            }.onFailure { android.util.Log.w("OscarUI", "Runtime update rejected", it) }
        }.start()
    }
}

class RuntimeScreenState(screen: JSONObject) {
    val values: SnapshotStateMap<String, Any> = mutableStateMapOf()
    val lists: Map<String, List<Map<String, Any>>>

    init {
        val listValues = mutableMapOf<String, List<Map<String, Any>>>()
        for (state in screen.objects("state")) {
            val name = state.string("name")
            if (state.string("type") == "list") {
                val rows = state.optJSONArray("default") ?: JSONArray()
                listValues[name] = (0 until rows.length()).mapNotNull { rows.optJSONObject(it) }.map { row ->
                    row.keys().asSequence().associateWith { key -> row.opt(key).runtimeValue() }
                }
            } else {
                values[name] = state.opt("default").runtimeValue()
            }
        }
        lists = listValues
    }
}

private fun Any?.runtimeValue(): Any = when (this) {
    null, JSONObject.NULL -> ""
    is String, is Boolean, is Int, is Long, is Double, is Float -> this
    is Number -> toDouble()
    else -> toString()
}
private fun Any?.display(): String = when (this) { null -> ""; is Boolean -> toString(); else -> this.toString() }
private fun Any?.truthy(): Boolean = when (this) { is Boolean -> this; is Number -> toDouble() != 0.0; is String -> isNotEmpty(); else -> false }

data class RuntimeContext(
    val props: Map<String, Any> = emptyMap(),
    val actionProps: Map<String, String> = emptyMap(),
    val item: Map<String, Any> = emptyMap(),
)

private interface RuntimeNavigator {
    fun navigate(screen: String)
    fun pop()
}

private class RuntimeStateNavigator(startDestination: String) : RuntimeNavigator {
    private val path = mutableStateListOf(startDestination)
    val currentRoute: String get() = path.last()
    override fun navigate(screen: String) { path.add(screen) }
    override fun pop() { if (path.size > 1) path.removeAt(path.lastIndex) }
}

private class RuntimeNavControllerNavigator(private val navController: NavHostController) : RuntimeNavigator {
    override fun navigate(screen: String) { navController.navigate(screen) }
    override fun pop() { navController.popBackStack() }
}

@Composable
fun RuntimeOscarApp() {
    val context = LocalContext.current
    val store = remember { RuntimeBundleStore(context) }
    val actions = remember { RuntimeNativeActions() }
    LaunchedEffect(Unit) { store.fetchRemoteUpdateIfConfigured() }
    key(store.bundle.contentHash) { RuntimeNavigation(store.bundle, actions) }
}

@Composable
private fun RuntimeNavigation(bundle: RuntimeBundle, actions: RuntimeNativeActions) {
    if (bundle.navigationAnimationsEnabled) RuntimePlatformNavigation(bundle, actions)
    else RuntimeStaticNavigation(bundle, actions)
}

@Composable
private fun RuntimePlatformNavigation(bundle: RuntimeBundle, actions: RuntimeNativeActions) {
    val navController = rememberNavController()
    val navigator = remember(navController) { RuntimeNavControllerNavigator(navController) }
    val backStackEntry by navController.currentBackStackEntryAsState()
    val currentRoute = backStackEntry?.destination?.route
    val tokens = RuntimeTokens(bundle.tokens)
    MaterialTheme {
        Surface(modifier = Modifier.fillMaxSize(), color = tokens.color("background")) {
            Box(Modifier.fillMaxSize()) {
                val navModifier = Modifier.padding(top = if (currentRoute != null && currentRoute != bundle.entryScreen) 56.dp else 0.dp)
                NavHost(navController = navController, startDestination = bundle.entryScreen, modifier = navModifier) {
                    runtimeRoutes(bundle, navigator, actions)
                }
                if (currentRoute != null && currentRoute != bundle.entryScreen) {
                    IconButton(
                        onClick = { navigator.pop() },
                        modifier = Modifier.align(Alignment.TopStart).statusBarsPadding().padding(8.dp)
                    ) { Text("‹", style = tokens.textStyle("title"), color = tokens.color("textPrimary")) }
                }
            }
        }
    }
}

@Composable
private fun RuntimeStaticNavigation(bundle: RuntimeBundle, actions: RuntimeNativeActions) {
    val navigator = remember(bundle.contentHash) { RuntimeStateNavigator(bundle.entryScreen) }
    val currentRoute = navigator.currentRoute
    val tokens = RuntimeTokens(bundle.tokens)
    MaterialTheme {
        Surface(modifier = Modifier.fillMaxSize(), color = tokens.color("background")) {
            Box(Modifier.fillMaxSize()) {
                Box(Modifier.padding(top = if (currentRoute != bundle.entryScreen) 56.dp else 0.dp)) {
                    RuntimeScreen(currentRoute, bundle, navigator, actions)
                }
                if (currentRoute != bundle.entryScreen) {
                    IconButton(
                        onClick = { navigator.pop() },
                        modifier = Modifier.align(Alignment.TopStart).statusBarsPadding().padding(8.dp)
                    ) { Text("‹", style = tokens.textStyle("title"), color = tokens.color("textPrimary")) }
                }
            }
        }
    }
}

private fun androidx.navigation.NavGraphBuilder.runtimeRoutes(
    bundle: RuntimeBundle,
    navigator: RuntimeNavigator,
    actions: RuntimeNativeActions,
) {
    for (screen in bundle.screens) {
        val name = screen.string("screen")
        composable(name) { entry -> RuntimeScreen(entry.destination.route ?: name, bundle, navigator, actions) }
    }
}

@Composable
private fun RuntimeScreen(name: String, bundle: RuntimeBundle, navigator: RuntimeNavigator, actions: RuntimeNativeActions) {
    val screen = bundle.screen(name) ?: return
    val state = remember(name, bundle.contentHash) { RuntimeScreenState(screen) }
    val layout = screen.optJSONObject("layout") ?: JSONObject()
    val tokens = RuntimeTokens(bundle.tokens)
    val modifier = Modifier.fillMaxSize().background(tokens.color("background"))
        .then(if (layout.optBoolean("safeArea", true)) Modifier.safeDrawingPadding() else Modifier)
    Box(modifier = modifier, contentAlignment = if (layout.string("contentPosition") == "center") Alignment.Center else Alignment.TopCenter) {
        RuntimeNodeGroup(
            nodes = screen.objects("body"), screen = screen, screenName = name, bundle = bundle,
            state = state, navigator = navigator, actions = actions, context = RuntimeContext(),
            modifier = tokens.contentWidthModifier(layout.string("contentWidth", "fill"))
        )
    }
}

@Composable
private fun RuntimeNodeGroup(
    nodes: List<JSONObject>, screen: JSONObject, screenName: String, bundle: RuntimeBundle,
    state: RuntimeScreenState, navigator: RuntimeNavigator, actions: RuntimeNativeActions,
    context: RuntimeContext, modifier: Modifier = Modifier,
) {
    if (nodes.size == 1) RuntimeNode(nodes[0], screen, screenName, bundle, state, navigator, actions, context, modifier)
    else Column(modifier) { nodes.forEach { RuntimeNode(it, screen, screenName, bundle, state, navigator, actions, context) } }
}

@Composable
private fun RuntimeNode(
    node: JSONObject, screen: JSONObject, screenName: String, bundle: RuntimeBundle,
    state: RuntimeScreenState, navigator: RuntimeNavigator, actions: RuntimeNativeActions,
    context: RuntimeContext, modifier: Modifier = Modifier,
) {
    fun resolve(binding: String): Any = when {
        binding.startsWith("item.") -> context.item[binding.removePrefix("item.")] ?: ""
        context.props.containsKey(binding) -> context.props[binding] ?: ""
        else -> state.values[binding] ?: ""
    }
    fun visible(): Boolean {
        val condition = node.optJSONObject("visibleWhen") ?: return true
        val actual = resolve(condition.string("state"))
        return when { condition.has("equals") -> actual == condition.opt("equals").runtimeValue(); condition.has("notEquals") -> actual != condition.opt("notEquals").runtimeValue(); else -> actual.truthy() }
    }
    fun perform(requested: String) {
        var action = requested
        val seen = mutableSetOf<String>()
        while (context.actionProps.containsKey(action) && seen.add(action)) action = context.actionProps[action].orEmpty()
        actions.invoke(screenName, action)
        val declaration = screen.objects("actions").firstOrNull { it.string("name") == action } ?: return
        val navigation = declaration.optJSONObject("navigation") ?: return
        when (navigation.string("type")) { "push" -> navigator.navigate(navigation.string("screen")); "pop" -> navigator.pop() }
    }
    if (!visible()) return
    val tokens = RuntimeTokens(bundle.tokens)
    when (node.string("type")) {
        "column" -> Column(
            modifier = modifier.padding(tokens.spacing(node.string("padding", "none"))),
            verticalArrangement = Arrangement.spacedBy(tokens.spacing(node.string("spacing", "normal"))),
            horizontalAlignment = when (node.string("align", "center")) { "start" -> Alignment.Start; "end" -> Alignment.End; else -> Alignment.CenterHorizontally }
        ) { node.objects("children").forEach { RuntimeNode(it, screen, screenName, bundle, state, navigator, actions, context) } }
        "row" -> Row(
            modifier = modifier.padding(tokens.spacing(node.string("padding", "none"))),
            horizontalArrangement = Arrangement.spacedBy(tokens.spacing(node.string("spacing", "normal"))),
            verticalAlignment = when (node.string("align", "center")) { "start" -> Alignment.Top; "end" -> Alignment.Bottom; else -> Alignment.CenterVertically }
        ) { node.objects("children").forEach { RuntimeNode(it, screen, screenName, bundle, state, navigator, actions, context) } }
        "text" -> Text(
            text = if (node.has("bind")) resolve(node.string("bind")).display() else node.string("value"),
            style = tokens.textStyle(node.string("role", "body")), color = tokens.color(node.string("color", "textPrimary")), modifier = modifier
        )
        "image" -> AsyncImage(
            model = node.string("url"), contentDescription = null, contentScale = ContentScale.Crop,
            modifier = modifier.fillMaxWidth().then(if (node.has("height")) Modifier.height(node.getDouble("height").dp) else Modifier).clip(RoundedCornerShape(tokens.radius(node.string("radius", "none"))))
        )
        "button" -> RuntimeButton(node, tokens, modifier) { perform(node.string("action")) }
        "textField" -> {
            val binding = node.string("bind")
            OutlinedTextField(
                value = state.values[binding].display(), onValueChange = { state.values[binding] = it },
                placeholder = { Text(node.string("placeholder"), style = tokens.textStyle("body"), color = tokens.color("placeholder")) },
                visualTransformation = if (node.optBoolean("secure")) PasswordVisualTransformation() else androidx.compose.ui.text.input.VisualTransformation.None,
                keyboardOptions = KeyboardOptions(keyboardType = when (node.string("keyboard", "default")) { "email" -> KeyboardType.Email; "number" -> KeyboardType.Number; "phone" -> KeyboardType.Phone; else -> KeyboardType.Text }),
                singleLine = true, textStyle = tokens.textStyle("body"), shape = RoundedCornerShape(tokens.radius("normal")),
                colors = OutlinedTextFieldDefaults.colors(focusedTextColor = tokens.color("textPrimary"), unfocusedTextColor = tokens.color("textPrimary"), focusedBorderColor = tokens.color("primary"), unfocusedBorderColor = tokens.color("border"), focusedContainerColor = tokens.color("fieldBackground"), unfocusedContainerColor = tokens.color("fieldBackground")),
                modifier = modifier.fillMaxWidth().height(tokens.size("controlHeight"))
            )
        }
        "list" -> {
            val items = state.lists[node.string("bind")].orEmpty()
            Column(modifier.clip(RoundedCornerShape(tokens.radius("normal"))).background(tokens.color("listRowBackground"))) {
                items.forEachIndexed { index, item ->
                    RuntimeNodeGroup(node.objects("itemTemplate"), screen, screenName, bundle, state, navigator, actions, RuntimeContext(context.props, context.actionProps, item))
                    if (index < items.lastIndex) HorizontalDivider(Modifier.padding(start = tokens.spacing("normal")), color = tokens.color("border"), thickness = tokens.size("borderWidth"))
                }
            }
        }
        "listRow" -> Row(
            modifier = modifier.fillMaxWidth().background(tokens.color("listRowBackground")).clickable { perform(node.string("action")) }.heightIn(min = tokens.size("listRowMinHeight")).padding(horizontal = tokens.spacing("normal"), vertical = tokens.spacing("tight")),
            verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(tokens.spacing("normal"))
        ) {
            Column(Modifier.weight(1f), verticalArrangement = Arrangement.spacedBy(tokens.spacing("tight"))) {
                Text(if (node.has("titleBind")) resolve(node.string("titleBind")).display() else node.string("title"), style = tokens.textStyle("body"), color = tokens.color("textPrimary"))
                if (node.has("subtitle") || node.has("subtitleBind")) Text(if (node.has("subtitleBind")) resolve(node.string("subtitleBind")).display() else node.string("subtitle"), style = tokens.textStyle("caption"), color = tokens.color("textSecondary"))
            }
            Text("›", style = tokens.textStyle("heading"), color = tokens.color("chevron"))
        }
        "component" -> bundle.component(node.string("name"))?.let { component ->
            val supplied = node.optJSONObject("props") ?: JSONObject()
            val props = mutableMapOf<String, Any>()
            val actionProps = context.actionProps.toMutableMap()
            for (definition in component.objects("props")) {
                val name = definition.string("name")
                val value = supplied.opt(name)
                if (definition.string("type") == "action") actionProps[name] = value as? String ?: ""
                else if (value is String && (value.startsWith("item.") || state.values.containsKey(value) || context.props.containsKey(value))) props[name] = resolve(value)
                else props[name] = value.runtimeValue()
            }
            RuntimeNodeGroup(component.objects("body"), screen, screenName, bundle, state, navigator, actions, RuntimeContext(props, actionProps, context.item), modifier)
        }
        "spacer" -> Spacer(modifier)
        else -> Text("Unsupported runtime node: ${node.string("type")}", color = Color.Red)
    }
}

@Composable
private fun RuntimeButton(node: JSONObject, tokens: RuntimeTokens, modifier: Modifier, onClick: () -> Unit) {
    val role = node.string("role", "primary")
    val content: @Composable () -> Unit = { Text(node.string("label"), style = tokens.textStyle("body")) }
    val sized = modifier.height(tokens.size("controlHeight")).widthIn(min = tokens.size("buttonMinWidth"))
    when (role) {
        "primary" -> Button(onClick, sized, colors = ButtonDefaults.buttonColors(containerColor = tokens.color("primary"), contentColor = tokens.color("onPrimary")), shape = RoundedCornerShape(tokens.radius("large")), content = { content() })
        "secondary" -> OutlinedButton(onClick, sized, colors = ButtonDefaults.outlinedButtonColors(contentColor = tokens.color("primary")), border = BorderStroke(tokens.size("borderWidth"), tokens.color("border")), shape = RoundedCornerShape(tokens.radius("large")), content = { content() })
        else -> TextButton(onClick, sized, colors = ButtonDefaults.textButtonColors(contentColor = tokens.color("primary")), content = { content() })
    }
}

class RuntimeTokens(private val values: JSONObject) {
    private fun number(group: String, name: String): Double = values.optJSONObject(group)?.optDouble(name, 0.0) ?: 0.0
    fun spacing(name: String): Dp = number("spacing", name).dp
    fun radius(name: String): Dp = number("radius", name).dp
    fun size(name: String): Dp = number("size", name).dp
    fun color(name: String): Color = Color(android.graphics.Color.parseColor(values.optJSONObject("color")?.string(name, "#000000") ?: "#000000"))
    fun textStyle(name: String): TextStyle {
        val definition = values.optJSONObject("typography")?.optJSONObject(name) ?: JSONObject()
        val weight = when (definition.string("weight")) { "bold" -> FontWeight.Bold; "semibold" -> FontWeight.SemiBold; else -> FontWeight.Normal }
        return TextStyle(fontSize = definition.optDouble("size", 16.0).sp, fontWeight = weight)
    }
    fun contentWidthModifier(name: String): Modifier = when (name) {
        "fill" -> Modifier.fillMaxWidth()
        else -> Modifier.widthIn(max = size("content" + name.replaceFirstChar { it.uppercase() })).fillMaxWidth()
    }
}
