// GENERATED BY aic — DO NOT EDIT. Source of truth: src/screens/*.ui.yaml and src/components/*.ui.yaml
package app.generated

import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.itemsIndexed
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.layout.ContentScale
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.unit.dp
import coil.compose.AsyncImage

interface ShowcaseActions {
}

@Composable
fun ShowcaseScreen(actions: ShowcaseActions, navigator: OscarNavigator) {
    var showImage by remember { mutableStateOf<Boolean>(true) }

    Box(
        modifier = Modifier.fillMaxSize().background(Theme.Colors.background),
        contentAlignment = Alignment.Center
    ) {
        Column(
            modifier = Modifier.fillMaxWidth().padding(Theme.Spacing.loose),
            verticalArrangement = Arrangement.spacedBy(Theme.Spacing.normal),
            horizontalAlignment = Alignment.CenterHorizontally
        ) {
            Row(
                horizontalArrangement = Arrangement.spacedBy(Theme.Spacing.tight),
                verticalAlignment = Alignment.CenterVertically
            ) {
                Text(
                    text = "Swift",
                    style = Theme.Typography.heading,
                    color = Theme.Colors.textPrimary
                )
                Spacer(modifier = Modifier.weight(1f))
                Text(
                    text = "Kotlin",
                    style = Theme.Typography.heading,
                    color = Theme.Colors.textPrimary
                )
            }
            if (showImage == true) {
                AsyncImage(
                    model = "https://example.com/oscarui.png",
                    contentDescription = null,
                    contentScale = ContentScale.Crop,
                    modifier = Modifier.fillMaxWidth().height(180.dp).clip(RoundedCornerShape(Theme.Radius.large))
                )
            }
        }
    }
}
